all: test1 test2 test3

test1: funkcja_power_test.c
		gcc funkcja_power_test.c -o test1

test2: funkcja_power_test2.c
		gcc funkcja_power_test2.c -o test2

test3: potegowanie.c
		gcc potegowanie.c -o test3
